from django.urls import path
from .views import (
    UserIDView,
    AddToCartView,
    OrderDetailView,
    AddCouponView,
    CountryListView,
    AddressListView,
    AddressCreateView,
    AddressUpdateView,
    AddressDeleteView,
    OrderItemDeleteView,
    OrderListView,
    OrderDoneView,
    GoogleLogin,
    ConfirmEmailView,
    VerifyEmailView,
    UserVerificationView,
    CategoryListView,
    CategoryDetailView

)

urlpatterns = [
    path('user-id/', UserIDView.as_view(), name='user-id'),
    path('countries/', CountryListView.as_view(), name='country-list'),
    path('addresses/', AddressListView.as_view(), name='address-list'),
    path('addresses/create/', AddressCreateView.as_view(), name='address-create'),
    path('addresses/<pk>/update/',
         AddressUpdateView.as_view(), name='address-update'),
    path('addresses/<pk>/delete/',
         AddressDeleteView.as_view(), name='address-delete'),
    path('products/', CategoryListView.as_view(), name='product-list'),
    path('products/<pk>/', CategoryDetailView.as_view(), name='product-detail'),
    path('add-to-cart/', AddToCartView.as_view(), name='add-to-cart'),
    path('order-summary/', OrderDetailView.as_view(), name='order-summary'),
    path('order-done/', OrderDoneView.as_view(), name='order-done'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('order-items/<pk>/delete/',
         OrderItemDeleteView.as_view(), name='order-item-delete'),
    path('google/', GoogleLogin.as_view(), name='goggle-login'),
    path('verify/', ConfirmEmailView.as_view(), name='goggle-login'),
    path('verify-last/', VerifyEmailView.as_view(), name='verify-email'),
    path('user-verification/', UserVerificationView.as_view(), name='goggle-login'),
    path('orders/', OrderListView.as_view(), name='goggle-login'),
]
