# Generated by Django 2.2.10 on 2020-05-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderitem_item_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification',
            field=models.BooleanField(default=False),
        ),
    ]
