# Generated by Django 2.2.10 on 2020-06-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orderitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='category',
        ),
    ]
